# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e549d7d5a0ec224078e72746bec6304e507a2d019cc06c9f09df2dac5a1f9dd4faa0059cba84e3e29f7da8f848705427612f91e5fe2971cc163dae63838033c

test:
  secret_key_base: dd65fc40506dbbb1e47cd4957890608a8a9a6ad0f64a9de002d9083d03a9d5df48e54f6e117dc933ddbc686ff815585d03dfa2e69740582146495768489ece89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
